services:
  rails:
    build: .
    tty: true
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa123456
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/scrappy
    working_dir: /scrappy
    depends_on:
      - db
      - redis # Asegura que Redis esté disponible antes de que inicie Rails

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
