services:
  rails:
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/scrappy # Monta la carpeta raiz 'scrappy' de tu sistema local en '/scrappy' dentro del contenedor
    working_dir: /scrappy # Define el directorio de trabajo para Rails
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
