require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/product_histories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProductHistory. As you add validations to ProductHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    category = create(:category)
    product = create(:product, category: category)
    {
      price: 100.0,
      product_id: Product.first.id
    }
  }

  let(:invalid_attributes) {
    {
      price: nil,
      product_id: nil
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProductHistory.create! valid_attributes
      get product_histories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      product_history = ProductHistory.create! valid_attributes
      get product_history_url(product_history)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_product_history_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      product_history = ProductHistory.create! valid_attributes
      get edit_product_history_url(product_history)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProductHistory" do
        expect {
          post product_histories_url, params: { product_history: valid_attributes }
        }.to change(ProductHistory, :count).by(1)
      end

      it "redirects to the created product_history" do
        post product_histories_url, params: { product_history: valid_attributes }
        expect(response).to redirect_to(product_history_url(ProductHistory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProductHistory" do
        expect {
          post product_histories_url, params: { product_history: invalid_attributes }
        }.to change(ProductHistory, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post product_histories_url, params: { product_history: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          price: 150.0,
          product_id: Product.first.id,
        }
      }

      it "updates the requested product_history" do
        product_history = ProductHistory.create! valid_attributes
        patch product_history_url(product_history), params: { product_history: new_attributes }
        product_history.reload
        expect(product_history.price).to eq(new_attributes[:price])
        expect(product_history.product_id).to eq(new_attributes[:product_id])
      end

      it "redirects to the product_history" do
        product_history = ProductHistory.create! valid_attributes
        patch product_history_url(product_history), params: { product_history: new_attributes }
        product_history.reload
        expect(response).to redirect_to(product_history_url(product_history))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        product_history = ProductHistory.create! valid_attributes
        patch product_history_url(product_history), params: { product_history: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested product_history" do
      product_history = ProductHistory.create! valid_attributes
      expect {
        delete product_history_url(product_history)
      }.to change(ProductHistory, :count).by(-1)
    end

    it "redirects to the product_histories list" do
      product_history = ProductHistory.create! valid_attributes
      delete product_history_url(product_history)
      expect(response).to redirect_to(product_histories_url)
    end
  end
end
