hello_world_job:
  cron: "* * * * *" # Cada minuto
  class: "HelloWorldJob"
  queue: default
scraping_job:
  cron: "*/2 * * * *" # Cada 5 minutos
  class: "ScrapingJob"
  queue: default
# price_check_job:
#   cron: "* * * * *" # Cada 5 minutos
#   class: "PriceCheckJob"
#   queue: default
