# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

      redis:
        image: redis:alpine
        ports:
          - "6379:6379"

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_URL: "redis://localhost:6379/0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.179.1
        with:
          ruby-version: 3.3.2
          bundler-cache: true

      - name: Fix bin/rails shebang
        run: sed -i '1s/.*/#!\/usr\/bin\/env ruby/' bin/rails

      - name: Set permissions for bin/rails
        run: chmod +x bin/rails

      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Precompile assets
        run: bundle exec rake assets:precompile

      # Run tests with RSpec
      - name: Run RSpec tests
        run: bundle exec rspec
